# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ImageEditor2 import Ui_MainWindow
import mysql.connector as mc


class Ui_Form(object):

    def ImageProcessor(self):
        self.window2 =  QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window2)
        self.window2.show()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(381, 473)
        Form.setMaximumSize(QtCore.QSize(400, 500))
        Form.setStyleSheet("background-color: rgb(31, 31, 31);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Background = QtWidgets.QStackedWidget(Form)
        self.Background.setStyleSheet("background-color: rgb(31, 31, 31);\n"
                                      "border: none;")
        self.Background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Background.setObjectName("Background")
        self.Login_Page = QtWidgets.QWidget()
        self.Login_Page.setObjectName("Login_Page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Login_Page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.Login_Page)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
                                   "color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMinimumSize(QtCore.QSize(100, 100))
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Icons/login.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.Login_Page)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.usernameInput = QtWidgets.QLineEdit(self.frame_3)
        self.usernameInput.setMinimumSize(QtCore.QSize(35, 35))
        self.usernameInput.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
                                         "background-color: rgba(85, 85, 85, 15);\n"
                                         "color: rgb(255, 255, 255);\n"
                                         "border: none;\n"
                                         "border-radius: 2px;\n"
                                         "border-bottom-style: solid;\n"
                                         "border-bottom-width: 2px;\n"
                                         "border-bottom-color: rgba(255, 255, 255, 150);")
        self.usernameInput.setObjectName("usernameInput")
        self.verticalLayout_2.addWidget(self.usernameInput)
        self.passwordInput = QtWidgets.QLineEdit(self.frame_3)
        self.passwordInput.setMinimumSize(QtCore.QSize(0, 35))
        self.passwordInput.setMaximumSize(QtCore.QSize(16777215, 35))
        self.passwordInput.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
                                         "background-color: rgba(85, 85, 85, 15);\n"
                                         "color: rgb(255, 255, 255);\n"
                                         "border: none;\n"
                                         "border-radius: 2px;\n"
                                         "border-bottom-style: solid;\n"
                                         "border-bottom-width: 2px;\n"
                                         "border-bottom-color: rgba(255, 255, 255, 150);\n"
                                         "")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.verticalLayout_2.addWidget(self.passwordInput)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.Login_Page)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.loginButton = QtWidgets.QToolButton(self.frame_4)
        self.loginButton.setMinimumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                       "border-radius: 10px")
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout_3.addWidget(self.loginButton, 0, QtCore.Qt.AlignHCenter)
        self.loginButton.clicked.connect(self.login)
        self.forgotPassword = QtWidgets.QToolButton(self.frame_4)
        self.forgotPassword.setMinimumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.forgotPassword.setFont(font)
        self.forgotPassword.setStyleSheet("QToolButton {\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "}\n"
                                          "QToolButton::hover{\n"
                                          "    color: blue;\n"
                                          "}")
        self.forgotPassword.setObjectName("forgotPassword")
        self.verticalLayout_3.addWidget(self.forgotPassword, 0, QtCore.Qt.AlignHCenter)
        self.labelResult = QtWidgets.QLabel(self.frame_4)
        self.labelResult.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                                       "color: rgb(255, 0, 15);\n"
                                       "color: rgb(221, 0, 0);")
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")
        self.verticalLayout_3.addWidget(self.labelResult, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_4)
        self.Background.addWidget(self.Login_Page)
        self.horizontalLayout.addWidget(self.Background)

        self.retranslateUi(Form)
        self.Background.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def login(self):
        try:
            username = self.usernameInput.text()
            password = self.passwordInput.text()

            mydb = mc.connect(
                host="localhost",
                user="root",
                database="health",
                password="mS50778609@21042001"
            )

            mycursor = mydb.cursor()
            query = "SELECT * FROM radiologists WHERE username = '%s' AND radpassword = '%s'" % (username, password)
            mycursor.execute(query)
            result = mycursor.fetchone()

            if result == None:
                self.labelResult.setText("Incorrect email or password!")

            else:
                self.labelResult.setText("You are logged in")
                self.window2 =  QtWidgets.QMainWindow()
                self.ui = Ui_MainWindow()
                self.ui.setupUi(self.window2)
                self.window2.show()
                Form.close()

        except mc.Error as e:
            self.labelResult.setText("Cannot connect to server")


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "BCDS LOGIN"))
        self.usernameInput.setPlaceholderText(_translate("Form", "Username"))
        self.passwordInput.setPlaceholderText(_translate("Form", "Password"))
        self.loginButton.setText(_translate("Form", "Log In"))
        self.forgotPassword.setText(_translate("Form", "Forgot Password?"))

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
